export const CREATE = 'CREATE';
export const GET_PAGE = 'GET_PAGE';
export const SET_DEFAULT_CREATED = 'SET_DEFAULT_CREATED';
export const GET_PAGE_NUMS = 'GET_PAGE_NUMS';
export const MAGAZINE_INITIATED = 'MAGAZINE_INITIATED';